version: '3'

services:
  nginx:
    build: .
    environment:
      API_KEY: ${API_KEY}
      OVERRIDE_HOSTNAME: mycoolhost
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
